const products = [
  {
    id: 1,
    name: "Aveeno Baby Daily Moisture Body Lotion for Sensitive Skin, Hypoallergenic Moisturizing Baby Lotion with Nourishing Oatmeal to Deeply Moisturize Baby's Skin, Fragrance-Free",
    photo: 'images/products/aveenoBabyLotion.png',
    tags: ['bath', 'skincare'],
    description: 'Baby Lotion',
    notes: '',
    link: 'https://www.amazon.com/Aveeno-Baby-Colloidal-Dimethicone-Fragrance-Free/dp/B0030UF6EW/',
  },
  {
    id: 2,
    name: 'KeaBabies Hooded Baby Towel for Newborn - Viscose Derived from Bamboo Large Baby Bath Towels with Hood for Boys, Girls, Toddler, Extra Absorbent & Soft Newborn Bath Essentials (Lamb)',
    photo: 'images/products/keababiesLambHoodedBabyTowel.png',
    tags: ['bath', 'clothing'],
    description: 'Baby Bath Towel',
    notes: '',
    link: 'https://www.amazon.com/Baby-Hooded-Towel-Organic-Newborn/dp/B0792344Z9/',
  },
  {
    id: 3,
    name: 'The Honest Company Clean Conscious Multi-Use Wipes | Hypoallergenic + Unscented for Sensitive Skin | Over 99% Water, Compostable, Plant Based, Baby Wipes',
    photo: 'images/products/honestBaby_Wipes.png',
    tags: ['diapers'],
    description: 'Baby Wipes',
    notes: '',
    link: 'https://www.amazon.com/Company-Conscious-Plant-Based-Hypoallergenic-Dermatologist/dp/B013C9OKVU/',
  },
  {
    id: 4,
    name: 'OsoCozy Prefolds Unbleached Cloth Baby Diapers',
    photo: 'images/products/osocozyPrefoldsClothDiapers.png',
    tags: ['diapers'],
    description: 'Cloth Diaper Inner Absorbent Lining',
    notes: '',
    link: 'https://www.amazon.com/OsoCozy-Prefolds-Unbleached-Absorbent-Best-Selling/dp/B003AJHDQW/',
  },
  {
    id: 5,
    name: "Dr. Brown's Natural Flow Level 1 Narrow Baby Bottle Silicone Nipple, Slow Flow, 0m+, 100% Silicone Bottle Nipple, 6 Count",
    photo: 'images/products/drbrownsSlowFlowNipples.png',
    tags: ['feeding'],
    description: 'Bottle Nipples',
    notes: '',
    link: 'https://www.amazon.com/Dr-Brown%C3%A2%E2%82%ACTMs-Natural-Narrow-Silicone/dp/B015XBYDG2/',
  },
  {
    id: 6,
    name: 'Tide Free & Gentle Liquid Laundry Detergent, 64 Loads, 84 fl oz, Tide Laundry Detergent, Clean Laundry Detergent',
    photo: 'images/products/tideGentleDetergent.png',
    tags: ['laundry'],
    description: 'Gentle Laundry Detergent',
    notes: '',
    link: 'https://www.amazon.com/Tide-Gentle-Liquid-Laundry-Detergent/dp/B085V5ZMV9/',
  },
  {
    id: 7,
    name: 'HALO SleepSack, 100% Cotton Wearable Blanket, Swaddle Transition Sleeping Bag, TOG 0.5, Cream, Newborn, 0-3 Months',
    photo: 'images/products/haloSleepsackSwaddleBlanket.png',
    tags: ['sleep', 'blanket'],
    description: 'Sleep Wearable Swaddle Blanket',
    notes: '',
    link: 'https://www.amazon.com/HALO-SleepSack-Wearable-Transition-Sleeping/dp/B007VFV93E/',
  },
  {
    id: 8,
    name: 'aden + anais Essentials Baby Muslin Swaddle Blankets, Newborn Receiving Blanket for Swaddling, 100% Cotton Baby Swaddle Wrap, 4 Pack, Country Floral',
    photo: 'images/products/adenAnaisSwaddleBlankets.png',
    tags: ['sleep', 'blanket'],
    description: 'Swaddle Blankets',
    notes: '',
    link: 'https://www.amazon.com/aden-anais-Essentials-Receiving-Swaddling/dp/B0CNKWGYXK/',
  },
  {
    id: 9,
    name: 'KeaBabies Baby Wrap Carrier - All in 1 Original Baby Carrier Newborn to Toddler Sling, Easy to Wear, Hands Free Bonding, Lightweight, Breathable Infant Wraps (Classic Gray)',
    photo: 'images/products/keababiesBabyWrapCarrier.png',
    tags: ['carrier', 'sling'],
    description: 'Baby Wrap Carrier',
    notes: '',
    link: 'https://www.amazon.com/Baby-Wrap-Carrier-Stretchy-Wraps/dp/B075GWFZRV/',
  },
  {
    id: 10,
    name: "Dr. Brown's Anti-Colic Options+ Narrow Glass Baby Bottle with Level 1 Slow Flow Nipple, BPA-Free",
    photo: 'images/products/drbrownsGlassBottle.png',
    tags: ['feeding'],
    description: 'Glass Bottles',
    notes: '',
    link: 'https://www.amazon.com/Dr-Browns-Natural-Options-Narrow/dp/B07WY1FH7N/',
  },
  {
    id: 11,
    name: "Simple Joys by Carter's 3-pack Sleep and Play",
    photo: 'images/products/cartersZipperedClothing.png',
    tags: ['sleep', 'clothing'],
    description: 'Sleep and Play Zippered Clothing',
    notes: '',
    link: 'https://www.amazon.com/Simple-Joys-Carters-Rainbows-Newborn/dp/B08G8TG866/',
  },
  {
    id: 12,
    name: 'b&h Baby Thermometer, The Infant Baby Bath Floating Toy Safety Temperature Water Thermometer (Classic Duck)',
    photo: 'images/products/bhBabyBathThermometer.png',
    tags: ['bath', 'safety', 'temperature'],
    description: 'Baby Bath Thermometer',
    notes: '',
    link: 'https://www.amazon.com/Thermometer-Infant-Floating-Safety-Temperature/dp/B073GGVN3Q/',
  },
  {
    id: 13,
    name: "Dr. Brown's Soft Touch No Scratch Baby Bottle Cleaning Brush Nipple Cleaner with Stand and Storage Clip, BPA Free, Blue 1-Pack",
    photo: 'images/products/drbrownsBottleBrush.png',
    tags: ['dishes'],
    description: 'Bottle Brush',
    notes: '',
    link: 'https://www.amazon.com/Dr-Browns-Touch-Bottle-Brush/dp/B01K7Z9SFA/',
  },
  {
    id: 14,
    name: "Dr. Brown's Drying Tower, Stand-Up Drying Rack, Countertop Baby Bottle Drying with Organized Storage for Baby Essentials, Space Saving Vertical Rack",
    photo: 'images/products/drbrownsDryingTower.png',
    tags: ['dishes'],
    description: 'Bottles Drying Tower',
    notes: '',
    link: 'https://www.amazon.com/Dr-Browns-Countertop-Organized-Essentials/dp/B0CMRV5CPZ/',
  },
  {
    id: 15,
    name: '[Toddler Size (Size 2) 5-Pack] Snappi Cloth Diaper Fasteners - Replaces Diaper Pins - Use with Cloth Prefolds and Flats',
    photo: 'images/products/snappiClothDiaperFasteners.png',
    tags: ['diapers'],
    description: 'Cloth Diaper Fasteners',
    notes: '',
    link: 'https://www.amazon.com/Toddler-5-Pack-Snappi-Diaper-Fasteners/dp/B071JMHMYT/',
  },
  {
    id: 16,
    name: 'DOQAUS Digital Hygrometer Indoor Thermometer for House, Room Thermometer with 3s Fast Refresh & Max Min Records, Temperature Monitor Humidity Meter with Backlight',
    photo: 'images/products/doquasIndoorHumidityTemperature.png',
    tags: ['safety', 'temperature'],
    description: 'Room Thermometer',
    notes: '',
    link: 'https://www.amazon.com/DOQAUS-Hygrometer-Thermometer-Temperature-Rechargeable/dp/B09WD7368D/',
  },
  {
    id: 17,
    name: 'The Honest Company 2-in-1 Cleansing Shampoo + Body Wash for Sensitive Skin | Gentle for Baby | Naturally Derived, Tear-free, Hypoallergenic | Fragrance Free',
    photo: 'images/products/honestBathShampoo.png',
    tags: ['bath'],
    description: 'Bath Shampoo',
    notes: '',
    link: 'https://www.amazon.com/Cleansing-Naturally-Tear-free-Hypoallergenic-Fragrance/',
  },
  {
    id: 18,
    name: 'The Honest Company Clean Conscious Diapers for Delicate Skin | Up to 100% Leakproof | Hypoallergenic, Fragrance Free | Gender Neutral | Club Box, Size Newborn',
    photo: 'images/products/honestDisposableDiapers.png',
    tags: ['diapers'],
    description: 'Disposable Diapers',
    notes: '',
    link: 'https://www.amazon.com/Honest-Company-Conscious-Plant-Based-Sustainable/dp/B0CKV2VGX1/',
  },
  {
    id: 19,
    name: 'Aeroflow BabyBuddha 2.0 Breast Pump',
    photo: 'images/products/babybuddhaBreastPump.png',
    tags: ['feeding'],
    description: 'Breast Pump',
    notes: '',
    link: 'https://aeroflowbreastpumps.com/baby-buddha-portable-double-electric-breast-pump?srsltid=AfmBOooQZmJ8yBrJsqRW4T0iIyP4NA0RxvrXJ8ISAvVYNawLDihoB9TE',
  },
  {
    id: 20,
    name: 'babygoal Newborn Baby Nail File 3 Pack with a Pouch, Emery Board Glass Crystal for Newborns, Toddlers, Infant, Babies & Young Children',
    photo: 'images/products/babygoalNewbornBabyFile.png',
    tags: ['nails'],
    description: 'Newborn Nail File',
    notes: '',
    link: 'https://www.amazon.com/Newborn-Crystal-Newborns-Toddlers-Children/dp/B07DXNNLML/',
  },
  {
    id: 21,
    name: 'Fisher-Price Baby to Toddler Bath 4-in-1 Sling ‘n Seat Tub with Removable Infant Support',
    photo: 'images/products/fisherpriceBathTub.png',
    tags: ['bath'],
    description: 'Bath Tub',
    notes: '',
    link: 'https://www.amazon.com/Fisher-Price-4-Sling-Seat-Tub/dp/B082N6GH9Z/',
  },
  {
    id: 22,
    name: 'Kanga Care Rumparooz Double Leg Gusset Reusable Cloth Diaper Cover One Size Snap',
    photo: 'images/products/rumparoozClothDiaperCover.png',
    tags: ['diapers'],
    description: 'Cloth Diaper Cover',
    notes: '',
    link: 'https://www.amazon.com/Kanga-Care-Rumparooz-Double-Reusable/dp/B0DXRQS1Y9/',
  },
  {
    id: 23,
    name: "Dr. Brown's Bottle & Dish Soap for Baby Bottles and Baby Accessories, Plant-Derived, Fragrance-Free",
    photo: 'images/products/drbrownsBottleSoap.png',
    tags: ['dishes'],
    description: 'Bottle Dish Soap',
    notes: '',
    link: 'https://www.amazon.com/Dr-Browns-Accessories-Plant-Derived-Fragrance-Free/dp/B0CG2FKPDR/',
  },
  {
    id: 24,
    name: 'Summer Infant Contoured Changing Pad',
    photo: 'images/products/contourChangingPad.png',
    tags: ['diapers'],
    description: 'Changing Pad',
    notes: '',
    link: 'https://www.amazon.com/Summer-Contoured-Changing-Pad-Quick-Release/dp/B09RSHL1CL/',
  },
];
